name: Install Script Workflow

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Echo example
        run: echo "Install script would run here"
